# Generated by Django 4.0.6 on 2023-07-04 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bioScienceApp', '0003_remove_protein_taxonomy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pfam',
            old_name='domain_id',
            new_name='domainId',
        ),
        migrations.RenameField(
            model_name='protein',
            old_name='protein_id',
            new_name='proteinId',
        ),
        migrations.RenameField(
            model_name='proteindomainlink',
            old_name='pfam_id',
            new_name='pfam',
        ),
        migrations.RenameField(
            model_name='taxonomy',
            old_name='taxa_id',
            new_name='taxaId',
        ),
    ]
