# Generated by Django 4.0.6 on 2023-06-29 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pfam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.CharField(max_length=256)),
                ('domain_description', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_id', models.CharField(max_length=256)),
                ('sequence', models.CharField(blank=True, max_length=256)),
                ('length', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa_id', models.CharField(max_length=256)),
                ('clade', models.CharField(blank=True, max_length=256)),
                ('genus', models.CharField(blank=True, max_length=256)),
                ('species', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ProteinDomainLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=256)),
                ('start', models.IntegerField(blank=True)),
                ('stop', models.IntegerField(blank=True)),
                ('pfam_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bioScienceApp.pfam')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bioScienceApp.protein')),
            ],
        ),
        migrations.AddField(
            model_name='protein',
            name='taxonomy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bioScienceApp.taxonomy'),
        ),
    ]
