# Generated by Django 4.0.6 on 2023-07-03 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bioScienceApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfam',
            name='domain_id',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='protein_id',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='proteindomainlink',
            name='protein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='domain', to='bioScienceApp.protein'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='taxa_id',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.CreateModel(
            name='TaxonomyProteinLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioScienceApp.protein')),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioScienceApp.taxonomy')),
            ],
            options={
                'unique_together': {('taxonomy', 'protein')},
            },
        ),
    ]
