from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser

from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status
from rest_framework import generics
from rest_framework.response import Response
from rest_framework.views import APIView

from .models import *
from .serializers import *


class GetCoverage(APIView):
    
    # return the domain coverage for a given protein. 
    # That is Sum of the protein domain lengths (start-stop)/length of protein.
    def get(self, request, protein_id):

        protein = get_object_or_404(Protein.objects.all(), proteinId=protein_id)
        coverage = protein.get_coverage()
        return Response({'coverage': coverage}, status=status.HTTP_200_OK)

    
class GetPfamOnTaxaId(generics.GenericAPIView):
    '''

    NOTE: "id" here is sequential the primary key value generated by django for the 
    table that holds the domain data - ProteinDomainLink
    
    '''
    serializer_class = GetPfamOnTaxaIdSerializer
    queryset = Taxonomy.objects.all()

    def get(self, request, taxa_id):
        taxonomy = get_object_or_404(Taxonomy, taxaId=taxa_id)
        #get all protein from link table with the same taxaid 
        taxonomyProteinLinks = TaxonomyProteinLink.objects.filter(taxonomy=taxonomy)
        
        #https://docs.djangoproject.com/en/4.2/ref/models/querysets/ - value list 
        proteinIds = taxonomyProteinLinks.values_list('protein', flat=True)

        #SELECT * FROM protein_domain_link WHERE protein_id IN (1, 2, 3);
        proteinDomainlinks = ProteinDomainLink.objects.filter(protein__in=proteinIds)
                
        pfam_data = self.serializer_class(proteinDomainlinks, many=True).data

        return Response(pfam_data, status=status.HTTP_200_OK)

'''
Return the domain and it's deacription on pfam_id
'''
class GetPfam (generics.GenericAPIView):
    serializer_class = PfamSerializer
    
    def get(self, request, pfam_id):
        pfam = get_object_or_404(Pfam.objects.all(), domainId=pfam_id)
        serializer = self.serializer_class(pfam)
        return Response(serializer.data, status=status.HTTP_200_OK)
    

'''
Return a list of all proteins for a given organism

not using serializers for customization, and it is simple code. 

NOTE: "id" here is sequential the primary key value generated by django
for the table that holds the domain data
'''

class GetTaxonomy(APIView):
    def get(self, request, taxa_id):
        queryset = Taxonomy.objects.all()
        taxonomy = get_object_or_404(queryset, taxaId=taxa_id)

        #get all protein from link table with the same taxaid 
        protein_Linked = TaxonomyProteinLink.objects.filter(taxonomy=taxonomy)
      
        data = [
            {"id": link.id, "protein_id":link.protein.proteinId}
            for link in protein_Linked
        ]

        return Response(data, status=status.HTTP_200_OK)

class GetProtein(generics.GenericAPIView):

    serializer_class = ProteinGetSerializer

    def get(self, request, protein_id):
         protien = get_object_or_404(Protein.objects.all(), proteinId=protein_id)
         serializer = self.serializer_class(protien)
         return Response(serializer.data, status=status.HTTP_200_OK)
          

class CreateProteins(APIView):
    serializer_class = ProteinSerializer

    def post(self, request):
                    
        domains_data = request.data.pop("domains", None)
        
        taxonomy = request.data.pop("taxonomy", None)
        
        protein_obj = self.create_protein(request.data)

        if taxonomy:
            taxonomy_obj =self.create_taxonomy(taxonomy)

        if domains_data:
            self.create_domains(protein_obj, domains_data)

        if taxonomy_obj and protein_obj:
            self.create_TaxonomyProteinLink(taxonomy_obj, protein_obj)


        return Response({'success':protein_obj.proteinId}, status=status.HTTP_201_CREATED)
   

    def create_protein(self, protein_data):
        protein_id = protein_data.get('protein_id')
               
        protein_obj = {}
        
        try:
            protein_obj = Protein.objects.get(proteinId=protein_id)
        except Protein.DoesNotExist:
            protein_obj = {}

        if not protein_obj: 
            serializer = ProteinSerializer(data=protein_data)
            serializer.is_valid(raise_exception=True)
            protein_obj = serializer.save()

        return protein_obj


    def create_taxonomy(self, taxonomy_data):

        taxa_id = taxonomy_data.get('taxa_id')
        taxonomy_obj = None

        try:
            taxonomy_obj = Taxonomy.objects.get(taxaId=taxa_id)
        except Taxonomy.DoesNotExist:
            taxonomy_obj = None

        if not taxonomy_obj:
            taxonomy_serializer = TaxonomySerializer(data=taxonomy_data)
            taxonomy_serializer.is_valid(raise_exception=True)
            taxonomy_obj = taxonomy_serializer.save()


        return taxonomy_obj


    def create_domains(self, protein, domains):

        domain_serialized = []
        
        for domain_data in domains:
            domain_data['protein'] = protein.id 
            pfam = domain_data.get('pfam_id')
            domain_id = pfam.get('domain_id')

            try: 
                pfam_obj = Pfam.objects.get(domainId=domain_id)
            except Pfam.DoesNotExist:
                pfam_obj = None

            if not pfam_obj: 
                link = ProteinDomainLinkSerializer(data=domain_data)
                domain_serialized.append(link)
                link.is_valid(raise_exception=True)
                link.save()    

    def create_TaxonomyProteinLink(self, taxonomy_obj, protein_obj):

        taxonomy_protein_link_data = {
        'taxonomy': taxonomy_obj.pk,
        'protein': protein_obj.pk
    }
        
        if not TaxonomyProteinLink.objects.filter(taxonomy=taxonomy_obj, protein=protein_obj).exists():
            taxaProLinkSerializer = TaxonomyProteinLinkSerializer(data=taxonomy_protein_link_data)
            taxaProLinkSerializer.is_valid(raise_exception=True)
            taxaProLinkSerializer.save()