import json
from django.test import TestCase
from django.urls import reverse
from django.urls import reverse_lazy

from rest_framework.test import APIRequestFactory
from rest_framework.test import APITestCase

from .model_factories import *
from .serializers import *
from rest_framework import status
from pprint import pprint

class ProteinTest(APITestCase):

    json_data = '''
        {
            "protein_id": "A0A016S8J7",
            "sequence": "MVIGVGFLLVLFSSSVLGILNAGVQLRIEELFDTPGHTNNWAVLVCTSRFWFNYRHVSNVLALYHTVKRLGIPDSNIILMLAEDVPCNPRNPRPEAAVLSA",
            "taxonomy": {
                "taxa_id": 53326,
                "clade": "E",
                "genus": "Ancylostoma",
                "species": "ceylanicum"
            },
            "length": 101,
            "domains": [
                {
                    "pfam_id": {
                        "domain_id": "PF01650",
                        "domain_description": "PeptidaseC13family"
                    },
                    "description": "Peptidase C13 legumain",
                    "start": 40,
                    "stop": 94
                },
                {
                    "pfam_id": {
                        "domain_id": "PF02931",
                        "domain_description": "Neurotransmitter-gatedion-channelligandbindingdomain"
                    },
                    "description": "Neurotransmitter-gated ion-channel ligand-binding domain",
                    "start": 23,
                    "stop": 39
                }
            ]
        }
        '''

    def test_createProtein(self):
        url = reverse('createProteins_api')
     
        json_obj = json.loads(self.json_data)
        response = self.client.post(url, json_obj, format='json')

        taxonomy = json_obj['taxonomy']
        taxa_id = taxonomy['taxa_id']

        domain_created = ProteinDomainLink.objects.all()
        pfams_created = Pfam.objects.all()
        organismCreated = Taxonomy.objects.get(taxaId=taxa_id)

        # check if all tables created.
        self.assertEqual(organismCreated.taxaId, str(taxa_id))
        self.assertEqual(len(domain_created), 2)
        self.assertEqual(len(pfams_created), 2)    
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
      


    def test_GetProtein(self):
        """
        endpoint test - api/protein/<str:protein_id>
        """
        protein = ProteinFactory.create()
        link1 = TaxonomyProteinLinkFactory.create(protein=protein)
        link2 = ProteinDomainLinkFactory.create(protein=protein)
        url = reverse('getProtein_api', kwargs={'protein_id': protein.proteinId})
        response = self.client.get(url)
        response.render()

        data = response.data
        json_obj = json.loads(self.json_data)

        self.assertEqual(response.status_code, 200)
        self.assertEqual(data['protein_id'], json_obj['protein_id'])
        self.assertEqual(data['sequence'], json_obj['sequence'])
        self.assertEqual(data['length'], json_obj['length'])
        
        #convering to dic and string 
        taxonomy_data = dict(data['taxonomy'])
        taxonomy_json_obj = {key: str(value) for key, value in json_obj['taxonomy'].items()}

        self.assertEqual(taxonomy_data, taxonomy_json_obj)
 
       
  
    def test_getTaxonomy(self):
        
        '''
        GET  http://127.0.0.1:8000/api/proteins/[TAXA ID] - return a list of all proteins for a given organism
        NOTE: "id" here is sequential the primary key value generated by django for the table that holds the domain data
        [
            {
                "id": <domain link factory pk>,
                "protein_id": <domain link protien, protein_id>
            },

        '''

        protein1 = ProteinFactory.create(proteinId='A0A1234567') 

        protein2 = ProteinFactory.create(proteinId='A0A134567') 

        link1 = TaxonomyProteinLinkFactory.create(protein=protein1)
        taxonomy = link1.taxonomy
        taxa_id = link1.taxonomy.taxaId

        link2 = TaxonomyProteinLinkFactory.create(protein=protein2, taxonomy=taxonomy)

        
        url = reverse('getTaxonomy_api', kwargs={'taxa_id': taxa_id})
        response = self.client.get(url)

        response.render()
        self.assertEqual(response.status_code, 200)
        
        taxonomy = get_object_or_404(Taxonomy.objects.all(), taxaId=taxa_id)

        protein_Linked = TaxonomyProteinLink.objects.filter(taxonomy=taxonomy)
      
        expected_data = [
            {"id": link.id, "protein_id": link.protein.proteinId}
            for link in protein_Linked
        ]
                
        self.assertEqual(response.data, expected_data)

    def test_getPfam_api(self):
        '''
        endpoint = api/pfam/<str:pfam_id>

        path('api/pfam/<str:pfam_id>', api.GetPfamas_view(), name='getPfam_api'),

        http://127.0.0.1:8000/api/pfam/PF00360 returns
        {
            "domain_id": "PF00360",
            "domain_description": "Phytochromeregion"
        }
        '''
        link1 = ProteinDomainLinkFactory.create()
        pfam_id = link1.pfam.domainId
        url = reverse('getPfam_api', kwargs={'pfam_id': pfam_id})
        response = self.client.get(url)
        response.render()
        self.assertEqual(response.status_code, 200)

        expected_data = {"domain_id": pfam_id, "domain_description": link1.pfam.domain_description}

        self.assertEqual(response.data, expected_data)



    def test_GetPfamOnTaxaId(self):
            
        '''
        path('api/pfams/<int:taxa_id>', api.GetPfamOnTaxaId.as_view(), 
        name='getPfamOnTaxaId_api'),  

        return a list of all domains in all the proteins for a given organism.
        
        NOTE: "id" here is sequential the primary key value generated by django for the table that holds the domain data
        http://127.0.0.1:8000/api/pfams/55661 returns
        [
            {
                "id": 88896,
                "pfam_id": {
                    "domain_id": "mobidb-lite",
                    "domain_description": "disorder prediction"
                }
            },
               
        '''

        taxonomy = Taxonomy.objects.create(taxaId='55661')
        protein1 = ProteinFactory.create(proteinId='A0A1234567') 
        protein2 = ProteinFactory.create(proteinId='A0A134567') 

        link1 = TaxonomyProteinLinkFactory.create(protein=protein1, taxonomy=taxonomy)
        link2 = TaxonomyProteinLinkFactory.create(protein=protein2, taxonomy=taxonomy)

        pfam1 = Pfam.objects.create(domainId='domain1', domain_description='Description 1')
        pfam2 = Pfam.objects.create(domainId='domain2', domain_description='Description 2')

        taxonomy = link1.taxonomy
        taxa_id = link1.taxonomy.taxaId

        link1Pfam = ProteinDomainLinkFactory.create(protein=protein1, pfam=pfam1)
        link2Pfam = ProteinDomainLinkFactory2.create(protein=protein2, pfam=pfam2)
        
        url = reverse('getPfamOnTaxaId_api', kwargs={'taxa_id': taxa_id})
        response = self.client.get(url)
        response.render()
        
        self.assertEqual(response.status_code, 200)

        expected_data1 = {"id": "1", "pfam_id": {"domain_id": "domain1", "domain_description": "Description 1"}}
        expected_data2 = {"id": "2", "pfam_id": {"domain_id": "domain2", "domain_description": "Description 2"}}
        
        response_data_list = response.data
        response_data_1 = response_data_list[0]
        response_data_2 = response_data_list[1]

        self.assertEqual(response_data_1, expected_data1)
        self.assertEqual(response_data_2, expected_data2)




    def test_GetCoverage(self):
        '''
        path('api/coverage/<str:protein_id>', api.GetCoverage.as_view(), name='getCoverage_api'),

        GET  http://127.0.0.1:8000/api/coverage/[PROTEIN ID] - return the domain coverage for a given protein. That is Sum of the protein domain lengths (start-stop)/length of protein.
        http://127.0.0.1:8000/api/coverage/A0A016S8J7 returns
        coverage:	0.693069306930693

        '''

        protein = ProteinFactory()

        domain1 = PfamFactory(domainId='PF01650', domain_description='PeptidaseC13family')
        domain2 = PfamFactory(domainId='PF12345', domain_description='AnotherDomain')


        domain_link1 = ProteinDomainLinkFactory(protein=protein, pfam=domain1)
        domain_link2 = ProteinDomainLinkFactory(protein=protein, pfam=domain2)

        protein_id = protein.proteinId

        url = reverse('getCoverage_api', kwargs={'protein_id': protein_id})
        response = self.client.get(url)
        
        self.assertEqual(response.status_code, status.HTTP_200_OK)

        domains = ProteinDomainLink.objects.filter(protein__proteinId=protein_id)
        
        domain_lengths = sum(domain.stop - domain.start for domain in domains)
        expected_coverage = domain_lengths / protein.length

        response_data = response.data
        response_coverage = response_data['coverage']

        self.assertEqual(response_coverage, expected_coverage)

