import json
from django.test import TestCase
from django.urls import reverse
from django.urls import reverse_lazy

from rest_framework.test import APIRequestFactory
from rest_framework.test import APITestCase

from .model_factories import *
from .serializers import *
from rest_framework import status

class ProteinTest(APITestCase):

    json_data = '''
        {
            "protein_id": "A0A016S8J7",
            "sequence": "MVIGVGFLLVLFSSSVLGILNAGVQLRIEELFDTPGHTNNWAVLVCTSRFWFNYRHVSNVLALYHTVKRLGIPDSNIILMLAEDVPCNPRNPRPEAAVLSA",
            "taxonomy": {
                "taxa_id": 53326,
                "clade": "E",
                "genus": "Ancylostoma",
                "species": "ceylanicum"
            },
            "length": 101,
            "domains": [
                {
                    "pfam_id": {
                        "domain_id": "PF01650",
                        "domain_description": "PeptidaseC13family"
                    },
                    "description": "Peptidase C13 legumain",
                    "start": 40,
                    "stop": 94
                },
                {
                    "pfam_id": {
                        "domain_id": "PF02931",
                        "domain_description": "Neurotransmitter-gatedion-channelligandbindingdomain"
                    },
                    "description": "Neurotransmitter-gated ion-channel ligand-binding domain",
                    "start": 23,
                    "stop": 39
                }
            ]
        }
        '''

    def test_createProtein(self):
        url = reverse('createProteins_api')
     
        json_obj = json.loads(self.json_data)
        response = self.client.post(url, json_obj, format='json')

        print(response.content)

        # taxonomy = json_obj['taxonomy']
        # taxa_id = taxonomy['taxa_id']

        # domain_created = ProteinDomainLink.objects.all()
        # pfams_created = Pfam.objects.all()
        # organismCreated = Taxonomy.objects.get(taxaId=taxa_id)

        #check if all tables created.
        # self.assertEqual(organismCreated.taxaId, str(taxa_id))
        # self.assertEqual(len(domain_created), 2)
        # self.assertEqual(len(pfams_created), 2)    
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
      


    # def test_GetProtein(self):
    #     """
    #     endpoint test - api/protein/<str:protein_id>
    #     """
    #     protein_id = ProteinFactory.create(protein_id="A0A016S8J7")
    #     url = reverse('getProtein_api', kwargs={'protein_id': protein_id})
    #     response = self.client.get(url)
    #     response.render()

    #     print(response.data)
    #     self.assertEqual(response.status_code, 200)


    
    # def test_getTaxonomy(self):
        
    #     '''
       
    #     GET  http://127.0.0.1:8000/api/proteins/[TAXA ID] - return a list of all proteins for a given organism
    #     NOTE: "id" here is sequential the primary key value generated by django for the table that holds the domain data

    #     '''

    #     link1 = ProteinDomainLinkFactory.create()
    #     taxa_id = link1.protein.taxonomy.taxa_id
        

    #     taxonomy = get_object_or_404(Taxonomy.objects.all(), taxa_id=taxa_id)
    #     proteins = taxonomy.get_proteins()
    #     protein_data = ProteinTaxaSerializer(proteins, many=True).data

    #     expected_data = [
    #         {"id": taxa_id, "protein_id": protein["protein_id"]}
    #         for protein in protein_data
    #     ]


    #     url = reverse('getTaxonomy_api', kwargs={'taxa_id': taxa_id})
    #     response = self.client.get(url)
    #     response.render()
    #     print(response.data)
    #     self.assertEqual(response.status_code, 200)
    #     self.assertEqual(response.data, expected_data)




    # #path('api/pfam/<str:pfam_id>', api.GetPfam.as_view(), name='getPfam_api'),
    # def test_getPfam_api(self):
    #     '''
    #     endpoint = api/pfam/<str:pfam_id>
    #     '''
    #     pfam_id = PfamFactory.create()
    #     url = reverse('getPfam_api', kwargs={'pfam_id': pfam_id})
    #     response = self.client.get(url)
    #     response.render()
    #     self.assertEqual(response.status_code, 200)

    
    # def test_getPfam(self):
    #     '''
    #     end point path 'api/pfam/<str:pfam_id>'
    #     return the domain and it's deacription
    #     '''
        
    #     link1 = ProteinDomainLinkFactory.create()
    #     taxa_id = link1.protein.taxonomy.taxa_id

    #     pfam_id = link1.pfam_id
    
    #     expected_data = {
    #         "domain_id": pfam_id.domain_id,
    #         "domain_description": link1.pfam_id.domain_description
    #     }

    #     url = reverse('getPfam_api', kwargs={'pfam_id': pfam_id})
    #     response = self.client.get(url)
    #     response.render()
    #     self.assertEqual(response.status_code, 200)
    #     self.assertEqual(response.data, expected_data)




